#!/usr/bin/env bash

# Update package list
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Start Nginx service
sudo systemctl start nginx

# Enable Nginx to start on boot
sudo systemctl enable nginx

# Create a configuration file for the redirection
echo "server {
    listen 80;
        server_name deenyshomar.tech; # Replace with your actual domain or server IP

	    location /redirect_me {
	            return 301 http://deenyshomar.tech; # Replace with the actual destination URL
		        }

		    # Additional server configuration can be added here if needed
	    }" | sudo tee /etc/nginx/sites-available/3-redirection

    # Create a symbolic link to enable the site
    sudo ln -s /etc/nginx/sites-available/3-redirection /etc/nginx/sites-enabled/

    # Test Nginx configuration
    sudo nginx -t

    # Reload Nginx to apply changes
    sudo systemctl reload nginx

    # Display a message indicating successful configuration
    echo "Nginx configured for redirection. Access http://deenyshomar.tech redirect_me to see the redirection."

